# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkMFA-8THmslnV8jeV33fWuUqWe2WEVB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df=pd.read_csv('homeprices.csv')
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area(sqr ft)')
plt.ylabel('price(US$)')
plt.scatter(df.area,df.price,color='blue',marker='*')

reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

reg.predict([[5000]])

reg.coef_

reg.intercept_

135.78767123*3300+180616.43835616432

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area', fontsize=20)
plt.ylabel('price', fontsize=20)
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,reg.predict(df[['area']]),color='blue')

d=pd.read_csv('areas.csv')
d.head(3)

p=reg.predict(d)

d['prices']=p

d.to_csv("prediction.csv",index=False)



