# -*- coding: utf-8 -*-
"""Linear_Reg_GivenTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKYQWYrTPmgs1YdSC_HDErcw2y94Q1YT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df=pd.read_csv('/content/canada_per_capita_income.csv')
df

df.head()

df.tail()

#Independent and dependent variables
x=df[['year']]
y=df[['per capita income (US$)']]

#Train the Model
model=LinearRegression()
model.fit(x,y)

prediction= model.predict([[2020]])
prediction

print("Predicted per Capita Income in 2020: ${:.2f}".format(prediction[0][0]))

